import './globals.css'
import { Roboto, Teko } from "next/font/google";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const tekoFont = Teko({
  subsets: ["latin"],
  display: "swap",
  weight:["300", "400", "500", "600", "700"]
});


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={tekoFont.className}>
      <body>{children}</body>
    </html>
  )
}
